[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["src/lib/**", "src/types/**"] # Include shared lib and types

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Scheduled function to fetch daily jobs
[functions."fetch-daily-jobs"]
  schedule = "0 11 * * *" # Runs daily at 11:00 AM UTC (5:00 AM CST)

# CopilotKit runtime functions are removed as CopilotKit Cloud is being used.
# [functions."copilotkit-runtime"]
#   timeout = 60
#
# [functions."copilotkit-runtime-esm"]
#   timeout = 60
